version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${NESTJS_APP_PORT}:${NESTJS_APP_PORT}
    volumes:
      - ./src:/app/src
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
