version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch
      args:
        - ELK_VERSION=${ELK_VERSION}
    environment:
      - ES_JAVA_OPTS=-Xmx1G -Xms1G
    ports:
      - 9200:9200
      - 9300:9300
    # command:
    #   - sh
    #   - -c
    #   - 'elasticsearch-plugin install analysis-nori; /usr/local/bin/docker-entrypoint.sh elasticsearch;'
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/elasticsearch-plugins.yml:/usr/share/elasticsearch/config/elasticsearch-plugins.yml
    networks:
      - elastic
  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elastic

  nestjs-app:
    container_name: nestjs-app
    build:
      context: api
    ports:
      - ${NESTJS_APP_PORT}:${NESTJS_APP_PORT}
    volumes:
      - ./api/src:/app/src
    depends_on:
      - elasticsearch
    env_file: .env
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PORT=${ELASTIC_PORT}
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
