ARG ELK_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
# RUN bin/elasticsearch-plugin install analysis-nori
# RUN elasticsearch-plugin install analysis-nori
# CMD /usr/local/bin/docker-entrypoint.sh elasticsearch
